server:
  port: 8888

spring.datasource:
  url: jdbc:mysql://localhost:3307/weblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.tobycold.pojo
  configuration:
    map-underscore-to-camel-case: true
main:
  path: "D:\\weblog\\"
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  database: 0
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /index.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.tobycold.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    top:
      tobycold:
        mapper: debug
